### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by amr3k** [0xNima/Twideo#1]
Just read your message, sad to see this amazing bot shutting down.

Either way, take care of yourself 😌

**Comment by amr3k** [comment]
Worth mentioning that there is a great [open source android app](https://github.com/JunkFood02/Seal) that lets you download videos using youtube-dlp under the hood.

**Comment by 0xNima** [comment]
> Just read your message, sad to see this amazing bot shutting down.
> 
> Either way, take care of yourself 😌

Thank you 🙏🏻😊

**Comment by 0xNima** [comment]
> Worth mentioning that there is a great [open source android app](https://github.com/JunkFood02/Seal) that lets you download videos using youtube-dlp under the hood.

Wonderful project 👍🏻
